Update docker-image.yml with debug cmd

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,6 +13,12 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      - name: Debug - List Files in the Repository
+        run: ls -l
+
+      - name: Debug - Check for Dockerfile
+        run: ls -l Dockerfile || echo "Dockerfile not found!"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -23,4 +29,4 @@ jobs:
         run: docker build --file Dockerfile --tag vijay20397/fastapi:${{ github.sha }} .
 
       - name: Push Docker Image
-        run: docker push vijay20397/fastapi:${{ github.sha }}
+        run: docker push vijay20397/fastapi:${
